# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='image',
            field=models.URLField(default='/static/images/noimage.png'),
        ),
    ]
