# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_likes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='type',
        ),
        migrations.AddField(
            model_name='likes',
            name='liked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='since',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
