# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160329_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='image',
        ),
        migrations.AddField(
            model_name='performer',
            name='image',
            field=models.URLField(default='/static/images/noimage.png'),
        ),
    ]
