# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=256)),
                ('song', models.CharField(max_length=256)),
                ('embed_url', models.URLField()),
            ],
        ),
    ]
