# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20160410_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
