# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_ignoredevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 11, 12, 44, 22, 804419, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
