# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_likedcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('city', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='likedcity',
            name='name',
        ),
        migrations.AddField(
            model_name='likedcity',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.City'),
        ),
    ]
