# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20160424_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
